"""normalize timestamp columns to utc datetime2

Revision ID: 73bda2fc3df1
Revises: 7f9d0774546d
Create Date: 2026-08-22 16:34:37.159489

UTC timestamp normalization prerequisite for the Analytics & Dashboard
milestone - see docs/TECH_DEBT.md's "UTC timestamp normalization" entry for
the full investigation (empirical proof the SQL Server host's CURRENT_TIMESTAMP/
GETDATE() is local time, not UTC, and that DATETIME/DATETIME2 cannot itself
carry timezone information - only the "naive digits = UTC" convention this
migration establishes going forward can).

This migration does NOT touch any existing row's timestamp VALUES - it only
changes column TYPE (DATETIME -> DATETIME2(3)) and DEFAULT CONSTRAINTS
(CURRENT_TIMESTAMP -> SYSUTCDATETIME()). Existing rows keep whatever digits
they already had; those digits remain of unknown/DB-local basis until the
separately-approved dev-database reseed happens (not part of this
migration). Every row written AFTER this migration is UTC by construction,
via app.models.mixins + app.core.time.utc_now_naive.

25 audited system timestamp columns change type. Of those, exactly 22
currently carry a CURRENT_TIMESTAMP (stored internally by SQL Server as
"getdate()") default constraint and get it replaced with SYSUTCDATETIME().
The remaining 3 (tickets.resolved_at, tickets.closed_at,
comments.updated_at) are transition-specific, application-set-only fields -
they have no default today and none is added; only their type changes.

Existing default constraint names are SQL-Server-autogenerated
(e.g. "DF__attachmen__creat__6E01572D", confirmed via sys.default_constraints
on the real dev DB) - never hardcoded here, always discovered dynamically,
per the explicit requirement not to assume a generated name. The new
constraints this migration creates get deterministic, readable names
(df_<table>_<column>_utc) so a future migration never has to repeat this
discovery step for them.

One index touches an audited column and must be dropped/recreated around
its ALTER COLUMN: ix_inventory_transactions_company_item_created
(company_id, inventory_item_id, created_at) on inventory_transactions.
Confirmed via sys.indexes join sys.index_columns against the real dev DB
that no other index in the schema references any of these 25 columns.

TARGETED SEED-METADATA NORMALIZATION (final step of upgrade() only):
a completely fresh database still ends up with ~16 rows on the wrong time
basis even after everything above, because three *older*, already-applied
migrations seed static metadata via raw `CURRENT_TIMESTAMP` SQL that runs
*before* this migration in the chain, and this migration does not rewrite
other migrations:
  - e05a93267ebf (add_companies_table): one "Default Company" row,
    company_code='DEFAULT001', created_at AND updated_at both
    CURRENT_TIMESTAMP.
  - b8c5e972dfbf (add_priorities_table_and_migrate_ticket_priority_to_fk):
    four Priority rows, title IN ('Low','Medium','High','Critical'),
    created_at AND updated_at both CURRENT_TIMESTAMP (via that table's own
    now-superseded server_default, at the time it was created - later
    scoped to the Default Company by add_company_id_scoping).
  - 5aeede95b6be (backfill_inventory_categories_for_existing_companies):
    eleven InventoryCategory rows, name IN (the starter list below),
    created_at only (no updated_at column exists on this table)
    CURRENT_TIMESTAMP.

These are static system/default metadata, not user-generated history -
their original creation instant has no meaningful audit value (matches
this migration's approved design: normalize known seed rows to
SYSUTCDATETIME(), leave every real user/ticket/comment/attachment/
inventory-transaction/ticket-history row exactly as it is). Targeted by
stable business identifiers only, never a hardcoded numeric id:
Default Company by company_code; priorities by
(that company's id, title); inventory categories by
(that company's id, name). This can never touch a different, real
company's identically-named priority/category, since the company_id
predicate is always present. If a database's Default Company row has had
its company_code changed away from 'DEFAULT001' (the column is editable
via PATCH /companies/me), this step simply finds no match and is a no-op
for that database - it does not guess or fall back to an id.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql


# revision identifiers, used by Alembic.
revision: str = '73bda2fc3df1'
down_revision: Union[str, Sequence[str], None] = '7f9d0774546d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# (table, column, nullable) for all 25 audited columns.
_ALL_TIMESTAMP_COLUMNS: list[tuple[str, str, bool]] = [
    ("companies", "created_at", False),
    ("companies", "updated_at", False),
    ("departments", "created_at", False),
    ("departments", "updated_at", False),
    ("locations", "created_at", False),
    ("locations", "updated_at", False),
    ("priorities", "created_at", False),
    ("priorities", "updated_at", False),
    ("users", "created_at", False),
    ("users", "updated_at", False),
    ("tickets", "created_at", False),
    ("tickets", "updated_at", False),
    ("tickets", "resolved_at", True),
    ("tickets", "closed_at", True),
    ("inventory_items", "created_at", False),
    ("inventory_items", "updated_at", False),
    ("ticket_inventory_usage", "created_at", False),
    ("ticket_inventory_usage", "updated_at", False),
    ("categories", "created_at", False),
    ("attachments", "created_at", False),
    ("comments", "created_at", False),
    ("comments", "updated_at", True),
    ("inventory_categories", "created_at", False),
    ("inventory_transactions", "created_at", False),
    ("ticket_history", "created_at", False),
]

# Exactly the 3 fields with no default today, before and after this migration.
_NO_DEFAULT_COLUMNS = {("tickets", "resolved_at"), ("tickets", "closed_at"), ("comments", "updated_at")}

# The 22 remaining columns: CURRENT_TIMESTAMP -> SYSUTCDATETIME().
_DEFAULT_BEARING_COLUMNS = [
    (t, c, nullable)
    for (t, c, nullable) in _ALL_TIMESTAMP_COLUMNS
    if (t, c) not in _NO_DEFAULT_COLUMNS
]

_INDEX_NAME = "ix_inventory_transactions_company_item_created"
_INDEX_TABLE = "inventory_transactions"
_INDEX_COLUMNS = ["company_id", "inventory_item_id", "created_at"]

# The exact seed-metadata identifiers this migration normalizes - copied
# from the three source migrations named in this file's docstring, never
# re-derived or guessed.
_DEFAULT_COMPANY_CODE = "DEFAULT001"  # from e05a93267ebf
_SEEDED_PRIORITY_TITLES = ["Low", "Medium", "High", "Critical"]  # from b8c5e972dfbf
_SEEDED_INVENTORY_CATEGORY_NAMES = [  # from 5aeede95b6be
    "Laptop", "Desktop", "Monitor", "Printer", "Keyboard", "Mouse",
    "Dock", "Phone", "Network Equipment", "Cable", "Other",
]


def _existing_default_constraint_name(conn, table: str, column: str) -> str | None:
    """Look up the real (SQL-Server-autogenerated) name of a column's
    current default constraint - never assumed, always discovered, per
    this migration's explicit requirement."""
    return conn.execute(
        sa.text(
            """
            SELECT dc.name
            FROM sys.default_constraints dc
            JOIN sys.columns c
                ON c.object_id = dc.parent_object_id AND c.column_id = dc.parent_column_id
            WHERE dc.parent_object_id = OBJECT_ID(:table)
              AND c.name = :column
            """
        ),
        {"table": table, "column": column},
    ).scalar()


def _normalize_seed_metadata_timestamps(conn) -> None:
    """Rewrite created_at/updated_at to SYSUTCDATETIME() for exactly the
    known migration-seeded metadata rows (Default Company, its 4 starter
    priorities, its 11 starter inventory categories) - see this file's
    docstring for why these specific rows and no others. Every predicate
    is a stable business identifier (company_code / title / name) scoped
    through the Default Company's own id, never a hardcoded numeric id and
    never a bare title/name match that could reach another company's row.
    """
    company_id = conn.execute(
        sa.text("SELECT id FROM companies WHERE company_code = :code"),
        {"code": _DEFAULT_COMPANY_CODE},
    ).scalar()
    if company_id is None:
        # No Default Company by that code in this database (e.g. it was
        # renamed via PATCH /companies/me, or this is a database that
        # never had it) - nothing to safely target, so do nothing rather
        # than guess.
        return

    conn.execute(
        sa.text(
            "UPDATE companies SET created_at = SYSUTCDATETIME(), updated_at = SYSUTCDATETIME() "
            "WHERE id = :company_id"
        ),
        {"company_id": company_id},
    )

    title_params = {f"title{i}": t for i, t in enumerate(_SEEDED_PRIORITY_TITLES)}
    title_in = ", ".join(f":{k}" for k in title_params)
    conn.execute(
        sa.text(
            "UPDATE priorities SET created_at = SYSUTCDATETIME(), updated_at = SYSUTCDATETIME() "
            f"WHERE company_id = :company_id AND title IN ({title_in})"
        ),
        {"company_id": company_id, **title_params},
    )

    name_params = {f"name{i}": n for i, n in enumerate(_SEEDED_INVENTORY_CATEGORY_NAMES)}
    name_in = ", ".join(f":{k}" for k in name_params)
    conn.execute(
        sa.text(
            "UPDATE inventory_categories SET created_at = SYSUTCDATETIME() "
            f"WHERE company_id = :company_id AND name IN ({name_in})"
        ),
        {"company_id": company_id, **name_params},
    )


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()

    # 1. Drop the one index that references an audited column, so its
    # column can have its type changed.
    op.drop_index(_INDEX_NAME, table_name=_INDEX_TABLE)

    # 2. Drop the 22 existing (autogenerated-name) default constraints.
    for table, column, _nullable in _DEFAULT_BEARING_COLUMNS:
        name = _existing_default_constraint_name(conn, table, column)
        if name is not None:
            op.execute(sa.text(f"ALTER TABLE {table} DROP CONSTRAINT [{name}]"))

    # 3. Change all 25 columns from DATETIME to DATETIME2(3). No row data
    # is touched by this - it's a lossless, in-place type widening.
    for table, column, nullable in _ALL_TIMESTAMP_COLUMNS:
        op.alter_column(
            table,
            column,
            existing_type=sa.DateTime(),
            type_=mssql.DATETIME2(precision=3),
            nullable=nullable,
        )

    # 4. Recreate defaults on the 22 columns, now UTC-generating, with
    # deterministic names.
    for table, column, _nullable in _DEFAULT_BEARING_COLUMNS:
        op.execute(
            sa.text(
                f"ALTER TABLE {table} "
                f"ADD CONSTRAINT df_{table}_{column}_utc DEFAULT SYSUTCDATETIME() FOR {column}"
            )
        )

    # 5. Recreate the index dropped in step 1.
    op.create_index(_INDEX_NAME, _INDEX_TABLE, _INDEX_COLUMNS, unique=False)

    # 6. Normalize the known migration-seeded metadata rows only - see
    # _normalize_seed_metadata_timestamps and this file's docstring. No
    # user/ticket/comment/attachment/inventory-item/inventory-transaction/
    # ticket-history row is ever touched by this step.
    _normalize_seed_metadata_timestamps(conn)


def downgrade() -> None:
    """Downgrade schema.

    Does not attempt to revert step 6 of upgrade() - there is no correct
    "old" value to restore to (the original CURRENT_TIMESTAMP value was
    already wrong, which is the entire reason it was overwritten). Reverting
    the schema/defaults below is a clean, well-defined operation; reverting
    already-corrected static metadata timestamps to admittedly-wrong values
    would not be.
    """
    conn = op.get_bind()

    op.drop_index(_INDEX_NAME, table_name=_INDEX_TABLE)

    # Drop the deterministic-named UTC defaults this migration created.
    for table, column, _nullable in _DEFAULT_BEARING_COLUMNS:
        name = _existing_default_constraint_name(conn, table, column)
        if name is not None:
            op.execute(sa.text(f"ALTER TABLE {table} DROP CONSTRAINT [{name}]"))

    # Revert all 25 columns to plain DATETIME.
    for table, column, nullable in _ALL_TIMESTAMP_COLUMNS:
        op.alter_column(
            table,
            column,
            existing_type=mssql.DATETIME2(precision=3),
            type_=sa.DateTime(),
            nullable=nullable,
        )

    # Restore the original CURRENT_TIMESTAMP defaults on the 22 columns.
    for table, column, _nullable in _DEFAULT_BEARING_COLUMNS:
        op.execute(
            sa.text(f"ALTER TABLE {table} ADD DEFAULT CURRENT_TIMESTAMP FOR {column}")
        )

    op.create_index(_INDEX_NAME, _INDEX_TABLE, _INDEX_COLUMNS, unique=False)
