"""drop unused theme columns

Revision ID: aa1908b341bb
Revises: 73bda2fc3df1
Create Date: 2026-09-26 01:07:42.865922

Final schema cleanup: the "theme" concept (companies.theme, users.theme) was
stored and echoed by the API but never applied by any frontend - the
application has a single visual theme - so it is removed from the active
design rather than being kept as an unexplained, non-functional field.

Both columns held only the default value "light" in the development database
when this migration was written (1 company row, 4 user rows).

SQL Server detail: companies.theme was created with server_default='light',
which SQL Server implements as a default constraint with an autogenerated
name (e.g. "DF__companies__theme__19DFD96B"). A column cannot be dropped
while such a constraint exists, so it is discovered dynamically (never
hardcoded, same approach as 73bda2fc3df1) and dropped first. users.theme was
nullable with no server default, so it has no default constraint.

Historical migrations that created these columns (496ee3278515,
e05a93267ebf) are intentionally left untouched.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa1908b341bb'
down_revision: Union[str, Sequence[str], None] = '73bda2fc3df1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _default_constraint_name(conn, table: str, column: str) -> str | None:
    """The current (autogenerated) default constraint on table.column, if any."""
    return conn.execute(
        sa.text(
            """
            SELECT dc.name
            FROM sys.default_constraints dc
            JOIN sys.columns c
                ON c.object_id = dc.parent_object_id AND c.column_id = dc.parent_column_id
            WHERE dc.parent_object_id = OBJECT_ID(:table)
              AND c.name = :column
            """
        ),
        {"table": table, "column": column},
    ).scalar()


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()

    constraint = _default_constraint_name(conn, "companies", "theme")
    if constraint is not None:
        # Alembic's drop_constraint has no "default" type; same raw form
        # 73bda2fc3df1 uses for the same reason.
        op.execute(sa.text(f"ALTER TABLE companies DROP CONSTRAINT [{constraint}]"))
    op.drop_column("companies", "theme")
    op.drop_column("users", "theme")


def downgrade() -> None:
    """Downgrade schema.

    Restores the columns exactly as they were: companies.theme NOT NULL with
    server default 'light' (existing rows are filled with 'light'), and
    users.theme nullable. Existing users get NULL - the value the column had
    for any row not explicitly set - which the old code treated as "no
    preference"; there was never any behavior attached to it.
    """
    op.add_column(
        "companies",
        sa.Column("theme", sa.String(length=20), nullable=False, server_default="light"),
    )
    op.add_column("users", sa.Column("theme", sa.String(length=20), nullable=True))
